### ISSUE TITLE
vis.js network hierarchical many nodes shown a line

### ISSUE THREAD

**Issue by lasclocker** [vagaerg/Tango_with_django#1]
Excuse me, I see your question on stackOverFlow, 
http://stackoverflow.com/questions/38479282/vis-js-not-showing-graph-when-many-nodes-are-added
how do you solve it at last? My email address: lasclocker@163.com
Thank you very much!
With my best wishes!

**Comment by vagaerg** [comment]
The issue is, as far as we could find, unrelated to our code but an issue in the vis.js library. If the style of the graph is changed from hierarchical to any of the other available ones, it works fine.

My suggestion is to either debug the library or find another one. Sorry.
